version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5009:5009"
    environment:
      # from gitaction sercet - .env
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - NODE_ENV=production
      - PORT=5009
      # Connects to the redis service internally within Docker Bridge network
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
   #internally 