name: Build and Deploy (GHCR to VPS)

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: amber-bisht/zorvyn

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Deploying via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROD_ENV: ${{ secrets.PROD_ENV }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          password: ${{ secrets.VPS_PASSWORD }}
          envs: GITHUB_TOKEN,PROD_ENV
          script: |
            mkdir -p ~/assignment
            cd ~/assignment
            
            # Robust Git Pull
            if [ ! -d ".git" ]; then
              git init
              git branch -M main
            fi
            
            git remote remove origin || true
            git remote add origin https://oauth2:$GITHUB_TOKEN@github.com/Amber-bisht/zorvyn.git
            git fetch origin main
            git reset --hard origin/main

            # Write environment variables
            echo "$PROD_ENV" > .env
            
            # Stop old containers
            docker compose down
            
            # Login to GHCR to allow pulling of private images without "denied: denied" error
            echo "$GITHUB_TOKEN" | docker login ghcr.io -u Amber-bisht --password-stdin
            
            # Pull the latest image built by GHCR
            docker compose pull
            
            # Start up
            docker compose up -d
