name: Deploy Backend to VPS Using Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          # Automatically provided by GitHub Actions for cloning
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Securely pass the .env content
          PROD_ENV: ${{ secrets.PROD_ENV }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          password: ${{ secrets.VPS_PASSWORD }}
          envs: GITHUB_TOKEN,PROD_ENV
          script: |
            # Safely create directory and enter it
            mkdir -p ~/assignment
            cd ~/assignment
            
            # Use ephemeral GITHUB_TOKEN to bypass "Username/Password" prompts
            if [ -d ".git" ]; then
              git remote set-url origin https://oauth2:$GITHUB_TOKEN@github.com/Amber-bisht/zorvyn.git
              git pull origin main
            else
              git clone https://oauth2:$GITHUB_TOKEN@github.com/Amber-bisht/zorvyn.git .
            fi

            # Safely write the production environment variables
            echo "$PROD_ENV" > .env
            
            # Restart docker containers detached mode, forcing build
            docker compose down
            docker compose up -d --build
